export const appointments = [
  {
    id: 1,
    patientName: "Aarav Sharma",
    age: 32,
    gender: "Male",
    contact: "+91 9876543210",
    doctor: "Dr. Meena Kapoor",
    department: "Cardiology",
    appointmentDate: "2025-08-28",
    appointmentTime: "10:30 AM",
    status: "Scheduled",
    reason: "Chest pain and shortness of breath",
  },
  {
    id: 2,
    patientName: "Priya Nair",
    age: 28,
    gender: "Female",
    contact: "+91 9988776655",
    doctor: "Dr. Rajesh Kumar",
    department: "Dermatology",
    appointmentDate: "2025-08-28",
    appointmentTime: "11:00 AM",
    status: "Completed",
    reason: "Skin allergy and itching",
  },
  {
    id: 3,
    patientName: "Rahul Verma",
    age: 45,
    gender: "Male",
    contact: "+91 9123456789",
    doctor: "Dr. Sneha Iyer",
    department: "Neurology",
    appointmentDate: "2025-08-29",
    appointmentTime: "09:45 AM",
    status: "Cancelled",
    reason: "Frequent headaches and dizziness",
  },
  {
    id: 4,
    patientName: "Kavya Reddy",
    age: 36,
    gender: "Female",
    contact: "+91 9012345678",
    doctor: "Dr. Amitabh Singh",
    department: "Orthopedics",
    appointmentDate: "2025-08-29",
    appointmentTime: "02:15 PM",
    status: "Scheduled",
    reason: "Knee pain after injury",
  },
  {
    id: 5,
    patientName: "Mohammed Ali",
    age: 52,
    gender: "Male",
    contact: "+91 9098765432",
    doctor: "Dr. Neha Bhatia",
    department: "General Medicine",
    appointmentDate: "2025-08-30",
    appointmentTime: "04:00 PM",
    status: "Scheduled",
    reason: "Routine health checkup and blood test",
  },
];
